name: Publish Python Package to PyPI

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest

    environment:
      name: pypi
      url: https://pypi.org/p/aes-bridge

    permissions:
      id-token: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        ref: ${{ github.event.release.tag_name }}

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build twine

    - name: Update pyproject.toml version
      run: |
        RELEASE_TAG="${{ github.event.release.tag_name }}"
        VERSION_TO_SET="${RELEASE_TAG#v}"
        sed -i "s/^version = \".*\"/version = \"${VERSION_TO_SET}\"/" pyproject.toml
      shell: bash

    - name: Build sdist and wheel
      run: python3 -m build

    - name: Publish package to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
